package com.ccy.chuchaiyi.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table USER_INFO.
 */
public class UserInfo implements Serializable{

    private static final long serialVersionUID = -6584791188571113237L;
    private String Token;
    private Integer EmployeeId;
    private String EmployeeName;
    private String Mobile;
    private String Email;
    private Boolean IsAdmin;
    private Boolean IsGreenChannel;
    private Boolean CanBookingForOthers;
    private Integer CorpId;
    private String CorpName;
    private String CorpBusinessTypes;
    private String CorpPayMode;
    private Boolean ApprovalRequired;
    private String OverrunOption;
    private Boolean IsProjectRequired;

    public UserInfo() {
    }

    public UserInfo(String Token, Integer EmployeeId, String EmployeeName, String Mobile, String Email, Boolean IsAdmin, Boolean IsGreenChannel, Boolean CanBookingForOthers, Integer CorpId, String CorpName, String CorpBusinessTypes, String CorpPayMode, Boolean ApprovalRequired, String OverrunOption, Boolean IsProjectRequired) {
        this.Token = Token;
        this.EmployeeId = EmployeeId;
        this.EmployeeName = EmployeeName;
        this.Mobile = Mobile;
        this.Email = Email;
        this.IsAdmin = IsAdmin;
        this.IsGreenChannel = IsGreenChannel;
        this.CanBookingForOthers = CanBookingForOthers;
        this.CorpId = CorpId;
        this.CorpName = CorpName;
        this.CorpBusinessTypes = CorpBusinessTypes;
        this.CorpPayMode = CorpPayMode;
        this.ApprovalRequired = ApprovalRequired;
        this.OverrunOption = OverrunOption;
        this.IsProjectRequired = IsProjectRequired;
    }

    public String getToken() {
        return Token;
    }

    public void setToken(String Token) {
        this.Token = Token;
    }

    public Integer getEmployeeId() {
        return EmployeeId;
    }

    public void setEmployeeId(Integer EmployeeId) {
        this.EmployeeId = EmployeeId;
    }

    public String getEmployeeName() {
        return EmployeeName;
    }

    public void setEmployeeName(String EmployeeName) {
        this.EmployeeName = EmployeeName;
    }

    public String getMobile() {
        return Mobile;
    }

    public void setMobile(String Mobile) {
        this.Mobile = Mobile;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public Boolean getIsAdmin() {
        return IsAdmin;
    }

    public void setIsAdmin(Boolean IsAdmin) {
        this.IsAdmin = IsAdmin;
    }

    public Boolean getIsGreenChannel() {
        return IsGreenChannel;
    }

    public void setIsGreenChannel(Boolean IsGreenChannel) {
        this.IsGreenChannel = IsGreenChannel;
    }

    public Boolean getCanBookingForOthers() {
        return CanBookingForOthers;
    }

    public void setCanBookingForOthers(Boolean CanBookingForOthers) {
        this.CanBookingForOthers = CanBookingForOthers;
    }

    public Integer getCorpId() {
        return CorpId;
    }

    public void setCorpId(Integer CorpId) {
        this.CorpId = CorpId;
    }

    public String getCorpName() {
        return CorpName;
    }

    public void setCorpName(String CorpName) {
        this.CorpName = CorpName;
    }

    public String getCorpBusinessTypes() {
        return CorpBusinessTypes;
    }

    public void setCorpBusinessTypes(String CorpBusinessTypes) {
        this.CorpBusinessTypes = CorpBusinessTypes;
    }

    public String getCorpPayMode() {
        return CorpPayMode;
    }

    public void setCorpPayMode(String CorpPayMode) {
        this.CorpPayMode = CorpPayMode;
    }

    public Boolean getApprovalRequired() {
        return ApprovalRequired;
    }

    public void setApprovalRequired(Boolean ApprovalRequired) {
        this.ApprovalRequired = ApprovalRequired;
    }

    public String getOverrunOption() {
        return OverrunOption;
    }

    public void setOverrunOption(String OverrunOption) {
        this.OverrunOption = OverrunOption;
    }

    public Boolean getIsProjectRequired() {
        return IsProjectRequired;
    }

    public void setIsProjectRequired(Boolean IsProjectRequired) {
        this.IsProjectRequired = IsProjectRequired;
    }

}
